language: java
script:
- mvn install -f releng/org.eclipse.emf.ecp.vaadin.releng/pom.xml
- ./releng/org.eclipse.emf.ecp.vaadin.releng.repository/deploy-p2.sh
env:
  global:
  - secure: WK8jJp/p6ImcfYxCxWMTlED9tFokoQcgr0MlSfciQiqCEIKb87i7b4bf6Qelap0ZOM1ZgPU7b1cGZKyap+oxcSrP5ZlNp5GXotfplV32/KyNGYHCIHioARQajIsY1guHxiN3iTGc5xB4Mme/c9o28uB654Ge3m9qiUY334i//pQ=
  - secure: AKPUKWrewGaDCzvmqY0J+vQyazT7gtKybHEsDgT2ynxK28om+EZ/C0s2lj/7rpulyoE+hT3kTZmC09S4ivnFBI588oginY+5nsW0A6sOwuhXSWW2jgZ1fqHQeZ6wdbv+z23bbJhKlQck1k8t1QVIo2cbrAwgAfD8Kf+z3C4b6+4=
  - secure: bGutwsaS5z6BZyUaTJKk65l16mTmWFtOkseCDE4i7o+vPIFnti/E8pUSoqVXMLQhERNdu+vCEfpAMi6i4A0G+JsCK3C8UQldDhkJdNwqF1lmNaW2HXCa2OqyrC0PC9+VO4qOFKvX7bu73R60ZD3uC1CJ3/Zvgh764MpGDdgYBg8=
