<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test" nsURI="http://eclipse/org/emf/ecp/test" nsPrefix="test">
  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gender" eType="#//Gender"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="active" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeOfRegistration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="heigth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nationality" eType="#//Nationality"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateOfBirth" eType="#//DateOfBirth"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Gender">
    <eLiterals name="Male"/>
    <eLiterals name="Female" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Nationality">
    <eLiterals name="German" literal="German"/>
    <eLiterals name="French"/>
    <eLiterals name="UK"/>
    <eLiterals name="US"/>
    <eLiterals name="Spanish"/>
    <eLiterals name="Italian"/>
    <eLiterals name="Russian"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DateOfBirth" instanceClassName="javax.xml.datatype.XMLGregorianCalendar">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="http://www.eclipse.org/emf/2003/XMLType#date"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
